### PR TITLE
Create greetings.yml

### PR DESCRIPTION
**Pull request by N3v1**
Hi @SID262000 @Devansh-Singh-Parmar,
Have you some ideas for a message that could be displayed?

### CODE REVIEW

**Comment by SID262000** [comment]
Feel free to take a call here.
cc: @Devansh-Singh-Parmar @neelansh27 @Atrika10 @AryanGupta0007 @Maghish

**Comment by neelansh27** [comment]
I think it's better not to be too specific since we don't know what's the reason for pull request or issue opening.

For Issues:
We acknowledge the opening of your first issue with gratitude. You will hear from our team regarding this issue soon.

For Pull Request:
We embrace your collaboration through this pull request and look forward to achieving great things .

Feel free to make some changes @N3v1

**Comment by N3v1** [comment]
done @neelansh27 @SID262000 @Devansh-Singh-Parmar

**Comment by N3v1** [comment]
can i merge? @SID262000

**Comment by N3v1** [comment]
@Devansh-Singh-Parmar

**Review by Devansh-Singh-Parmar — APPROVED** [review]
Great!

**Comment by SID262000** [comment]
Great work @N3v1!
cc: @Devansh-Singh-Parmar

**Pull request merged**
