### PR TITLE
Docs/contribute.md

### PR DESCRIPTION
**Pull request by AryanGupta0007**
Hey @SID262000  i have added the contribute.md and also kept in mind the changes made by @Devansh-Singh-Parmar and @N3v1 in their discussion and also added the neccesary guidelines missing in their PR. #33

### CODE REVIEW

**Comment by SID262000** [comment]
Cc: @Devansh-Singh-Parmar @N3v1 for feedback before accepting/discarding this PR

**Comment by Devansh-Singh-Parmar** [comment]
We are still adding more things in PR created by me, please wait
cc: @AryanGupta0007 @SID262000

**Comment by AryanGupta0007** [comment]
I think since our Project has many contributors at the moment and many of them don't have Knowledge of git and also we are visited by many people through diff. Sources i feel it's waste to delay adding a contribute.md so i feel we should merge one PR if everything is right and gradually make changes in it to make it perfect as if we go for a perfect PR maybe it would take very long and i feel it's a waste of time considering the importance of contribute.md.
CC: @Devansh-Singh-Parmar @SID262000

**Comment by Devansh-Singh-Parmar** [comment]
It's right but we can just improve it a bit, already asked for a review from @SID262000

**Comment by SID262000** [comment]
I would like to have a final go signal from @N3v1 once he is back, before I finally review and merge the Contribution.md.
It is indeed one of the most important file before even open sourcing it, as it stands as a first reference point for any contributor looking to contribute.
cc: @AryanGupta0007 @Devansh-Singh-Parmar

**Comment by SID262000** [comment]
@AryanGupta0007 Please don't close any PR or Issue without confirmation, Thanks

**Comment by SID262000** [comment]
Reopening PR

**Comment by AryanGupta0007** [comment]
@SID262000 i have created a new PR INSTEAD OF THIS DUE TO SOME CHANGES IN IT

**Comment by SID262000** [comment]
You can continue making modifications in a single PR multiple times even after creating one.
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
@SID262000 ya i just googled it after making another PR. THANKS!

**Comment by Devansh-Singh-Parmar** [comment]
@SID262000 Please go on and merge

**Pull request closed without merging**
