### PR TITLE
Paste new Readme.md

### PR DESCRIPTION
**Pull request by N3v1**
Just one commit this time @SID262000

### CODE REVIEW

**Review by SID262000 — APPROVED** [review]
Great work, @N3v1 Really appreciate all your hard work and dedication!
We might need to circle back on the README once we have Contributions & LICENSE in-place. Many Thanks

**Comment by N3v1** [comment]
all good @SID262000 , just assign me the task

**Comment by Devansh-Singh-Parmar** [comment]
Check Contributing.md if any mistake there

**Comment by SID262000** [comment]
cc: @N3v1 Please follow up and acknowledge, Thanks

**Pull request merged**
