### PR TITLE
Readme updated and added necessary keyword labels 

### PR DESCRIPTION
**Pull request by KartikKar19**

### CODE REVIEW

**Review by N3v1 — CHANGES_REQUESTED** [review]
Hi @KartikKar19,
I think that too many labels are used

Maybe you can delete the following lables:
SCR-20230827-huuv
SCR-20230827-hvhx
SCR-20230827-hwbh
SCR-20230827-hwrj

Best regards
NH

cc: @SID262000

**Comment by N3v1** [comment]
Hi @KartikKar19 
I know working with labels can be tricky, but using too many labels will make the readme disorganized and reduce readability. In addition, the project seems unprofessional.

But nonetheless, I really appreciate your help.

Best regards
NH

**Comment by KartikKar19** [comment]
Ok I will make the changes accordingly

**Review by N3v1 — CHANGES_REQUESTED** [review]
@KartikKar19, see feedback here:

SCR-20230827-lyoi
SCR-20230827-lytx

cc: @SID262000

**Comment by SID262000** [comment]
Why was this PR closed without prior intimation.
cc: @KartikKar19 @N3v1

**Pull request closed without merging**
