### PR TITLE
Added contribute.md and updated .gitignore

### PR DESCRIPTION
**Pull request by AryanGupta0007**
hey @SID262000  i have added all the guidelines i felt were missing from @Devansh-Singh-Parmar 's PR and also added their @N3v1's changes suggested to @Devansh-Singh-Parmar  in my PR. and mistakenly added the updated gitgnore i mean i should have created a separate PR for different issues but it got together as it is like my 3rd time creating this PR from the past hour Git has devastated me so please bear with it this time and also i forgot to mention the issue in the commit as well. So this PR solves #33  and #52

### CODE REVIEW

**Comment by Devansh-Singh-Parmar** [comment]
I took this issue and after me and @N3v1 took the issue, do you think it's right to take the issue?

**Comment by AryanGupta0007** [comment]
@Devansh-Singh-Parmar What's the issue then?

**Comment by AryanGupta0007** [comment]
@Devansh-Singh-Parmar Didn't i ask for permission to create a PR where you said as you wish

**Comment by SID262000** [comment]
Looks like this PR is deleted before even being merged with the main.
cc: @AryanGupta0007 @Devansh-Singh-Parmar @N3v1

**Comment by AryanGupta0007** [comment]
@SID262000 yes i have created a different PR for contribute.md

**Comment by Devansh-Singh-Parmar** [comment]
Okay then @AryanGupta0007

**Pull request closed without merging**
