### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by N3v1**
Hi everyone 👋,
I created a license for you (see issue #36)

### CODE REVIEW

**Review by SID262000 — COMMENTED** [review]
Great work, @N3v1 
I would like to know, why have you proceeded with MIT License rather than any other open source licence.

**Comment by N3v1** [comment]
Hello @SID262000, Hello @Devansh-Singh-Parmar 👋,
I used the MIT license because I saw them using it (see your README.md). In addition, the MIT license with the GNU is the most common license. But if you want, I can change it.

Best regards,
NH

**Comment by SID262000** [comment]
Thanks @N3v1 for the review.
Please work with @Devansh-Singh-Parmar who is currently working on the Readme issue to get this sorted.
Attach some supporting evidence in this PR against the license chosen as the final call.

**Comment by Devansh-Singh-Parmar** [comment]
Sure @N3v1 We can work on this, you can update this with any other license and I'll do the same in Readme.md.

**Comment by N3v1** [comment]
Hi @Devansh-Singh-Parmar 👋,
**Which license** should I update the LICENSE.md to? I'm a bit confused right now. This is my first collaboration with several people right now.

**What license** do you want @SID262000?

Best regards,
NH

**Comment by SID262000** [comment]
We can discuss that @N3v1 and conclude based on the feasibility

**Comment by N3v1** [comment]
ok, thanks for your answer @SID262000

**Comment by SID262000** [comment]
Let me have a solid evidence on which License we would like to proceed with, I will update this thread accordingly. In case you find any supporting evidence to the best license, feel free to share it in this thread as well, Thanks
cc: @N3v1

**Comment by AryanGupta0007** [comment]
please update the changes in the PR. so that we can merge it 
cc: @N3v1

**Comment by N3v1** [comment]
Okay @AryanGupta0007, I'm doing it now in a new PR

**Comment by SID262000** [comment]
@N3v1 We already have a PR in place.
cc: @AryanGupta0007

**Pull request closed without merging**
