### PR TITLE
Added htmlhint and stylelint linter to pre-commit hook

### PR DESCRIPTION
**Pull request by neelansh27**
This PR resolves issue #110 
Along with the linters, I've also added an installation script which prompts the user to install the linters if they are not already available.
These linters have also been added as dev dependencies in the package.json file so if someone wants to install them manually, simply run: `npm install -D` and the linters will be installed.

cc: @SID262000

### CODE REVIEW

**Review by N3v1 — APPROVED** [review]
This appears satisfactory to me; however, the ultimate decision rests with @SID262000.

Waiting for @SID262000

**Comment by neelansh27** [comment]
Thanks for taking your time to review @N3v1

**Comment by Atrika10** [comment]
> This appears satisfactory to me; however, the ultimate decision rests with @SID262000.
> 
> Waiting for @SID262000

So, need to add @SID262000 as a reviewer.

**Review by SID262000 — APPROVED** [review]
Great work @neelansh27 . This is just amazing, it makes our codebase really clean!
cc: @Atrika10

**Pull request merged**
