### PR TITLE
Docs/contribute.md

### PR DESCRIPTION
**Pull request by AryanGupta0007**
added contribute.md #33 . this is my final PR for contribute.md
cc: @SID262000

### CODE REVIEW

**Comment by AryanGupta0007** [comment]
@SID262000 i think we should not wait more and merge one of the PR's and get over this issue

**Comment by SID262000** [comment]
cc @N3v1 for response.

**Comment by AryanGupta0007** [comment]
@Devansh-Singh-Parmar review this

**Comment by AryanGupta0007** [comment]
@Devansh-Singh-Parmar share your views i meant not review
cc: @SID262000

**Comment by SID262000** [comment]
@N3v1 Please review this PR, make any necessary changes required and give a green signal for merging it. Thanks

**Review by N3v1 — CHANGES_REQUESTED** [review]
Maybe fix the typos - Example: "***IF*** you are using virtualenv, install all the dependencies to your system by: `pip install -r requirements.txt`"

Write the f in small letters

Also do it in line 17

Line 27: Checkout - use a capital 'C'

Line 43-51: Remove extra space before the ':' 

Maybe link the LICENSE.md

**Comment by N3v1** [comment]
I apologize for the inconvenience @AryanGupta0007, but before @SID262000 can merge your PR, it needs to be revised and improved to include the edits I have requested. Thank you for your cooperation.

Thank you kindly 
Best regards
NH

**Comment by AryanGupta0007** [comment]
i have made the changes whereever required. Linking the License is not required as these are contribution guidelines and license has nothing to do with contribution. 
Thank you for the suggestions!
cc: @SID262000

**Review by N3v1 — CHANGES_REQUESTED** [review]
Hi @AryanGupta0007 👋,
These are the final adjustments that I would make:
- Line 19: Remove extra space before the ':'
- Line 23: Remove extra space between **if** and **there**

Thank you kindly 🙏
Best regards
NH

**Comment by AryanGupta0007** [comment]
Done @N3v1 
cc: @SID262000

**Review by N3v1 — APPROVED** [review]
Good job @AryanGupta0007

**Comment by N3v1** [comment]
@SID262000 The PR can be merged now 🟢

Best regards
NH

**Review by SID262000 — APPROVED** [review]
Thanks @N3v1 for reviewing the PR.
cc: @AryanGupta0007

**Pull request merged**
