### PR TITLE
Update SECURITY.md

### PR DESCRIPTION
**Pull request by N3v1**
@SID262000 I noticed that the version number in the Security.md file were wrong. Furthermore a wrong emoji was used.

## Changes

| old | new |
| :-----: | :------: |
| v0.x.x | v1.x.x |
| emoji ❌ | emoji ✅ |

### CODE REVIEW

**Comment by N3v1** [comment]
Can I merge this PR?

**Review by Devansh-Singh-Parmar — APPROVED** [review]

**Review by SID262000 — COMMENTED** [review]
@N3v1 Thanks for reporting and resolving the issue. I would say to be specific with the version number rather than having 1.x.x we should have 1.0.0 because that's already released. Please make the needful changes

**Comment by SID262000** [comment]
@N3v1 Do request the review just from one person otherwise it leads to a lot of conflicts.

**Comment by SID262000** [comment]
@Devansh-Singh-Parmar Kindly disapprove the review and revert the merged PR as there are still some changes required

**Comment by N3v1** [comment]
Yeah I agree with you but I think the future releases of DeliverEase will be also supported until version 2 but I can make the changes @SID262000

**Comment by SID262000** [comment]
Security files just list out the already released version, it doesn't take into account any of the future predicted releases.
cc: @N3v1

**Pull request merged**
