### PR TITLE
Fixed all pydocstyle errors

### PR DESCRIPTION
**Pull request by neelansh27**
@SID262000 I've added all the docstrings needed and also modified the one's already existing to fix all pydocstyle errors in the backend #8

### CODE REVIEW

**Review by N3v1 — APPROVED** [review]
@neelansh27 I unterstand now what I have to do. @SID262000 his changes are right 🟢

**Comment by SID262000** [comment]
Please make sure you have run pydocstyle and there aren't any reported issues or warnings. Also, let me know if you've by passed any, will need to investigate more on them.
Many Thanks @neelansh27 for taking this up so diligently!

**Comment by neelansh27** [comment]
@SID262000 pydocstyle is giving error for docstring in sphinx documentation folder, I'm not sure whether to include that file in the ignored files list in precommit hook since it's a configuration file or add docstrings in that file as well. There are no other files which are giving error or warnings when running pydocstyle.
**Path of file:** docs/conf.py

**Comment by SID262000** [comment]
Sphinx doesn't require docstring as Sphinx itself is generated from the docstring we provide.
You can add it to ignore during pre-commit checks.
cc: @neelansh27

**Comment by neelansh27** [comment]
I've added sphinx documentation to the ignored files list in the pre-commit hook.
I'm also **not facing** any **errors or warnings** while running pydocstyle @SID262000

**Review by SID262000 — APPROVED** [review]
Great work, @neelansh27
So right now, the entire codebase is 100 percent pydocstyle.

**Pull request merged**
