### PR TITLE
Toml file

### PR DESCRIPTION
**Pull request by AryanGupta0007**
Fixed issue #19. @SID262000

### CODE REVIEW

**Review by SID262000 — COMMENTED** [review]
I'm not totally sure if we are using all the mentioned packages, for example the tool.poetry. We might have to discuss this before moving on, Thanks
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
@SID262000 we are using all the required dependencies mentioned . These dependencies were generated by the virtual environment in the requirements.txt file which i have also included to the toml file .

**Comment by AryanGupta0007** [comment]
after a discussion with @SID262000 , i have to check out setuptools

**Comment by AryanGupta0007** [comment]
@N3v1 do you see any areas of improvisation here. Suggestions needed
cc: @SID262000

**Comment by N3v1** [comment]
Not really 🙁

**Comment by SID262000** [comment]
No worries, @N3v1 🙂

**Pull request merged**
