### PR TITLE
Formatting codebase using flake8, black, ruff

### PR DESCRIPTION
**Pull request by SID262000**
Format the entire Git repository with the above mentioned linters

### CODE REVIEW

**Comment by AryanGupta0007** [comment]
@SID262000 why not use a single linter instead of 3?

**Comment by SID262000** [comment]
@AryanGupta0007 Single linters unfortunately do not cover the entire PEP convention, so it's recommended to have the top 3 having maximum coverage of the PEP convention.

**Comment by AryanGupta0007** [comment]
@SID262000 can you provide a reference about use of double quotes instead of single, mentioned in the PEP guide as settings.py file is generated automatically hence i feel it's quite difficult that they don't follow PEP in their settings.py file.

**Comment by SID262000** [comment]
Setting.py is different in this context. 
Reference Link: https://pypi.org/project/black/
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
@SID262000 actually i meant settings.py is automatically generated by Django and when i checked the reference it shows that Django also uses Black as one of the linters hence i feel that changing the quotes from single to double in dictionaries was not required.

**Comment by SID262000** [comment]
Black uses double quotes by default.
cc: @AryanGupta0007

**Comment by SID262000** [comment]
Please approve & merge this PR, Thanks
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
Yes just reviewing all the files and merging this PR. @SID262000

**Comment by AryanGupta0007** [comment]
@SID262000  rest is fine but please add the import statement in the tests.py as it will be useful in future to add the testcases

**Comment by SID262000** [comment]
Once the test directories are in-place, will do the needful there as well, Thanks
cc: @AryanGupta0007

**Review by AryanGupta0007 — APPROVED** [review]

**Pull request merged**
