### PR TITLE
Fixed logging error in pre-commit hook

### PR DESCRIPTION
**Pull request by neelansh27**
The pre-commit hook was throwing error in git bash on Windows.  The error was occurring due to some issue in **black linter** and therefore I've added separate handling for black in the installation script.

### CODE REVIEW

**Comment by AryanGupta0007** [comment]
@neelansh27  The issue still persists.

**Comment by neelansh27** [comment]
Please check if the issue is resolved @AryanGupta0007

**Comment by AryanGupta0007** [comment]
Yes it has now @neelansh27

**Review by SID262000 — APPROVED** [review]
Many Thanks @neelansh27 @AryanGupta0007 for working together towards resolving this issue.

**Pull request merged**
