### PR TITLE
Readme updated and added necessary keyword labels and deleted unwanted labels #32

### PR DESCRIPTION
**Pull request by KartikKar19**
Issue number #32 resolved

### CODE REVIEW

**Comment by Devansh-Singh-Parmar** [comment]
Mergeable.
cc: @SID262000 @N3v1

**Comment by Devansh-Singh-Parmar** [comment]
Before you merge, @KartikKar19 can you please Shift the "Join us on Slack" button in "Social Media" section.
cc @SID262000 @KartikKar19 

image
 
talking about this.

**Comment by SID262000** [comment]
Let me know once it's ready to be merged. Thanks
cc: @Devansh-Singh-Parmar @KartikKar19

**Comment by KartikKar19** [comment]
image
In this preview its showing different though

**Comment by KartikKar19** [comment]
@Devansh-Singh-Parmar There is no GitHub wiki so the slack label is under social media only

**Comment by N3v1** [comment]
> @Devansh-Singh-Parmar There is no GitHub wiki so the slack label is under social media only

@Devansh-Singh-Parmar, there is a wiki on my fork.
See https://github.com/N3v1/DeliverEase/wiki

**Comment by KartikKar19** [comment]
Oh I see it now sorry will do the changes Thanks @Devansh-Singh-Parmar  @N3v1

**Comment by N3v1** [comment]
If you want the wiki to be on this repo you either have to give me write access or you have to create a wiki manually and copy the code from my wiki @Devansh-Singh-Parmar 

cc: @SID262000

**Review by N3v1 — APPROVED** [review]
I think its okay @KartikKar19 
@Devansh-Singh-Parmar Do you want any changes?

cc: @SID262000

**Comment by N3v1** [comment]
If @Devansh-Singh-Parmar is okay with the changes, @SID262000 can merge it

Waiting: @Devansh-Singh-Parmar 

cc: @KartikKar19

**Comment by SID262000** [comment]
Once @Devansh-Singh-Parmar gives a green signal, will merge it to the main. Thanks @KartikKar19 and @N3v1 for all the hard work!

**Comment by Devansh-Singh-Parmar** [comment]
Just a small change to increase looks! You can add labels to wiki link.
cc: @KartikKar19 @N3v1


note:- i'll be available from tomorrow 3pm IST, please wait for my green signal till then.

**Review by Devansh-Singh-Parmar — APPROVED** [review]
Great done!
You can merge it now @SID262000 

cc: @N3v1 @KartikKar19

**Pull request merged**
