### PR TITLE
Tests/backend

### PR DESCRIPTION
**Pull request by AryanGupta0007**
I have added the test cases for all the apps.  If you feel any more test is  needed for a particular function please comment down #67. 
cc: @SID262000

### CODE REVIEW

**Comment by SID262000** [comment]
Can you retry running the linters on the above files. Thanks
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
@SID262000 the linters have no effect on the test files
Cc: @neelansh27

**Review by SID262000 — APPROVED** [review]
Approving this, I hope it covers all the test cases which will be eventually displayed in the code coverage report. Thanks

**Comment by SID262000** [comment]
Looks like this PR has merged conflicts. Please resolve them, which will allow us to merge this into the main.
Cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
Creating a new PR then. @SID262000

**Pull request closed without merging**
