### PR TITLE
Added Git Hooks

### PR DESCRIPTION
**Pull request by neelansh27**
I've added a pre-commit hook and a commit-msg hook placed inside the hooks folder #9 .

**Pre-commit Hook:**
It consists of 2 function.
The first function analyses the code and provides feedback on potential errors, coding style violations, and other issues.
The second function runs tests from the Django test suite. Both of these functions will not allow the person to proceed further without resolving the issues.

**Commit-msg hook:**
It ensures that the commit message length is not more than 50 characters and it does not end with a period.

### CODE REVIEW

**Review by SID262000 — CHANGES_REQUESTED** [review]
I would like to add a couple of more linters alongside pydocstyle to check the documentation for Python codebase. Also, since this is a pre-commit hook we need to ensure it doesn't check files such as README,etc

**Comment by neelansh27** [comment]
I've added more linters alongside pydocstyle but the output generated was a lot and therefore I stored them in a linters.log file located inside the logs folder in the project's root and It will only contain logs from last time a person tries to commit.

> since this is a pre-commit hook we need to ensure it doesn't check files such as README,etc

All the linters that I've used perform checks on files ending with .py unless specified, However I excluded all the files in migrations folder since they are automatically generated.

**Comment by SID262000** [comment]
There are too many files as part of the recent PR, let's review them and get it in-place before merging it.
cc: @neelansh27

**Comment by neelansh27** [comment]
I've made the requested changes, please review them @SID262000 .

**Comment by SID262000** [comment]
Thanks for incorporating the changes, @neelansh27 
I'll work with you to test it on the local environment first before merging the above changes.

**Comment by SID262000** [comment]
At a high level, this would be our next high level action item.
-- identify all the files on the user's local branch that have been modified w/ respect to the branch off point from master. This should identify the following types of files, and implement linting correctly to them (e.g., should not lint deleted or untracked files): staged files, moved/renamed files, committed files, deleted files, untracked files
-- Files that have not been modified by the user should not raise linters errors
cc: @neelansh27

**Review by SID262000 — APPROVED** [review]

**Review by SID262000 — CHANGES_REQUESTED** [review]
@neelansh27 Please add steps to install the desired linters in case they don't exist on the system.

**Comment by neelansh27** [comment]
I've added the setup file. If someone runs into permission issues, it can be fixed by
`chmod +x <file_name>`

**THE SETUP FILE MUST BE RUN WITHIN THE _hooks FOLDER**

The pre-commit hook now prompts the user to install dependencies if they are not met.

**Review by SID262000 — APPROVED** [review]

**Pull request merged**
