### PR TITLE
Create bug_report.yml

### PR DESCRIPTION
**Pull request by N3v1**
Hi @SID262000, I created a .yml file for a new bug report form

For that, I created a .github/ISSUE_TEMPLATE folder

Best regards
NH

### CODE REVIEW

**Review by SID262000 — COMMENTED** [review]
Great! Can you explain what exactly this bug report does, and its area of application, Thanks
cc: @N3v1

**Comment by N3v1** [comment]
Hi @SID262000,
I've seen many other repos use bug reporting forms, so I thought it would be helpful if we could use it in this repo as well. 
Sometimes I feel like I don't know what to write in a bug report - in this situation, a bug report form would be helpful. If you don't have a bug report form, most people just write something like "function xy doesn't work" and don't provide any other helpful information like screenshots, descriptions, recreations, etc. 

An example of a repo using a bug report form is my Quick Convert repo - **see [here](https://github.com/N3v1/QuickConvert/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%F0%9F%94%B4+%3Cbug+name%3E)**.

If you click on the link you should see something like this:
Bildschirmfoto 2023-08-22 um 15 30 58

### The bug report form for this repo consists of 6 elements:
1. The description of the issue
```YAML
- type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what the bug is...
    validations:
      required: true
```
2. Steps to reliably reproduce the behavior
```YAML
- type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reliably reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
```
3. A clear and concise description of what you expected to happen
```YAML
- type: textarea
    attributes:
      label: Expected Behavior
      placeholder: >-
        A clear and concise description of what you expected to happen...
    validations:
      required: true
```
4. Any other context or considerations about the bug
```YAML
- type: textarea
    attributes:
      label: Additional Context
      placeholder: >-
        Any other context or considerations about the bug...
```
5. Screenshots
```YAML
- type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        If applicable, please provide relevant screenshots or screen recordings...
```
6. Checkbox - "Is there an existing issue for this?"
```YAML
- type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
```

In the first lines of the bug_report.yml file you can find something like that:
```YAML
name: 🔴 Bug report
description: Something is not working as expected.
title: 🔴 <bug name>
labels: bug
```
- The "Name" and "Description" sections are for template selection when creating a new issue
- The title is the title of the issue
- Labels are applied to the bug report in the Labels sections

--- 

If you have any other questions, just let me know
Best regards
NH

**Comment by N3v1** [comment]
@SID262000, if you want I can create a feature request form

**Review by SID262000 — APPROVED** [review]
I see. Great work, Many Thanks @N3v1 for compiling this bug report.

**Comment by N3v1** [comment]
Hi @SID262000,
I added a config.yml and a feature_request.yml in the lastest commit.

## What does the config.yml do?
With the config.yml you can configure the issue template selection:
- I added this file to allow others to open a blank issue if there isn't a template that fits their issue
```YAML
blank_issues_enabled: true
```
- Then I added a third selection to open a new discussion to get help
```YAML
contact_links:
  - name: DeliverEase Support
    url: https://github.com/orgs/TeamCodeArena/discussions
    about: Please ask and answer questions here.
```

Bildschirmfoto 2023-08-22 um 16 13 05

---

Furthermore, I created a feature request form that functions the same as the bug report just with small changes:
- Description
```YAML
- type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what you would like to happen...
    validations:
      required: true
```
- Any alternative solutions or features you've considered
```YAML
- type: textarea
    attributes:
      label: Alternatives Considered
      placeholder: >-
        Any alternative solutions or features you've considered...
```
- Additional Context
```YAML
- type: textarea
    attributes:
      label: Additional Context
      placeholder: >-
        Any other context or considerations about the feature request...
```
- Screenshots
```YAML
- type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        If applicable, please provide relevant screenshots or screen recordings...
```
- checkboxes
```YAML
- type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you encountered.
      options:
      - label: I have searched the existing issues
        required: true
```

**Pull request merged**
