### PR TITLE
N3v1 link product page repo

### PR DESCRIPTION
**Pull request by N3v1**
Hi @SID262000, @Devansh-Singh-Parmar, @AryanGupta0007,
In this PR I liked the deliverease.app repo for the product page to the README.md. Furthermore, I created a new logo for you I'm waiting for Siddhant's review. I also have to change the logo on the top of the readme

# Tasks:

- [x] Change Logo
- [x] Redesign Readme
- [x] Link deliverease.app to the README

### CODE REVIEW

**Review by SID262000 — APPROVED** [review]
This is really great! @N3v1 
Many Thanks for your initiative on the design front.

**Comment by N3v1** [comment]
Hi everyone, @SID262000, @Devansh-Singh-Parmar,  
Can I create a new Markdown file named `Status.md` to store badges since the Readme is quite messy?

**Comment by N3v1** [comment]
> **Note** \
> When we are done with the logo, we just have to paste the new path of the image -> 
```MD
<p align="center">
  <img src="img/LogoDeliverEase.png" height="128"> // paste new logo in the img folder and link it here
  <h1 align="center">DeliverEase</h1>
</p>
```

**Comment by SID262000** [comment]
@N3v1 If you feel the need to modify the existing README, please perform an estimate of effort first, followed by investigation on the existing README and figuring out the loopholes.
Based on the above, we might proceed with creating a separate file as mentioned from your end in the preceding message, feel free to create a new issue to track down the above listed action items. Thanks

**Comment by N3v1** [comment]
@SID262000 Can you please discuss with the others at the meeting which logo should be used.

cc: @Devansh-Singh-Parmar

**Comment by Devansh-Singh-Parmar** [comment]
I'll do it @N3v1 
Cc @N3v1

**Comment by N3v1** [comment]
Thanks @Devansh-Singh-Parmar 
cc: @SID262000

**Comment by SID262000** [comment]
Please take this item at the top priority during today's weekly meeting.
cc: @Devansh-Singh-Parmar @N3v1 
Accordingly also update the thread!

**Comment by Devansh-Singh-Parmar** [comment]
Sure @SID262000 
Cc @N3v1

**Comment by N3v1** [comment]
@SID262000 @Devansh-Singh-Parmar Which logo should we use now? What have you discussed?

**Comment by Devansh-Singh-Parmar** [comment]
Hey @SID262000 @N3v1 and everyone!

We will be using this logo from now, please everyone do changes in website according to this color theme only!
cc @N3v1 @SID262000 

logo

**Comment by N3v1** [comment]
Okay @Devansh-Singh-Parmar

**Comment by N3v1** [comment]
We can implement this icon without problems on our product page @SID262000 @Devansh-Singh-Parmar

**Comment by Devansh-Singh-Parmar** [comment]
Correct! go ahead @N3v1

**Comment by N3v1** [comment]
Tomorrow I’ll be done with the Readme @SID262000 @Devansh-Singh-Parmar

**Comment by N3v1** [comment]
Later I’ll mark this PR as Ready for Review - Sorry for the delay. Was really busy these days

cc: @SID262000 @Devansh-Singh-Parmar

**Comment by N3v1** [comment]
@SID262000 Can I merge it?
cc: @Devansh-Singh-Parmar

**Comment by SID262000** [comment]
Go ahead @N3v1

**Comment by Devansh-Singh-Parmar** [comment]
Good 🟢

**Comment by N3v1** [comment]
merged @SID262000 @Devansh-Singh-Parmar

**Comment by Devansh-Singh-Parmar** [comment]
Great @N3v1

**Pull request merged**
