### PR TITLE
Requirements.txt

### PR DESCRIPTION
**Pull request by AryanGupta0007**
added the file requirements.txt #29 . @SID262000

### CODE REVIEW

**Review by SID262000 — COMMENTED** [review]
I see you have deleted the toml file, is it that we can't have toml and requirements.txt both in the same project. Any supporting evidence for the same would be really appreciated, Thanks

**Comment by AryanGupta0007** [comment]
i have deleted the toml file only from the branch ( requirements.txt) as it is still is in the other branch and it is not relevant to this issue@SID262000

**Comment by AryanGupta0007** [comment]
hey @SID262000  I have confirmed that all the modules mentioned in this file are being used in our project.

**Review by SID262000 — APPROVED** [review]
Thanks for all the hard work @AryanGupta0007

**Pull request merged**
