### PR TITLE
N3v1 readesign readme.md

### PR DESCRIPTION
**Pull request by N3v1**
Hi @SID262000 👋,
Here is the new README.md, but it's not complete yet. May I create the Contribiute.md or is someone else already working on it? If someone else is working on it, we only need to link the file.

Thank you kindly 🙏
Best regards
NH

### CODE REVIEW

**Comment by SID262000** [comment]
@N3v1 There's already a WIP as PR for Contribution.md file. Please review it and work with @Devansh-Singh-Parmar to link it from Readme as appropriate, Thanks

**Review by SID262000 — COMMENTED** [review]
Please use git rebase -i to squash all the commits into one, otherwise related, to avoid creating 15 duplicate commit messages.

**Comment by N3v1** [comment]
? Is there a way to do it with the GithubDesktop-App?

**Comment by SID262000** [comment]
Looks like there is a way to perform the action using GitHub Desktop.
[Reference] (https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits-in-github-desktop%23:~:text%3DSquashing%2520a%2520commit,-In%2520GitHub%2520Desktop%26text%3DIn%2520the%2520list%2520of%2520branches,commits%2520using%2520Command%2520or%2520Shift%2520.&ved=2ahUKEwjqrZ7e88aAAxV0SWwGHRH-AyYQFnoECA0QBQ&usg=AOvVaw1fBn34y05Weg0_kg_2PDtU)

**Comment by Devansh-Singh-Parmar** [comment]
I am working on Contributor.md, if you have any suggestions please let us know

**Comment by N3v1** [comment]
> Looks like there is a way to perform the action using GitHub Desktop. [Reference] (https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits-in-github-desktop%23:~:text%3DSquashing%2520a%2520commit,-In%2520GitHub%2520Desktop%26text%3DIn%2520the%2520list%2520of%2520branches,commits%2520using%2520Command%2520or%2520Shift%2520.&ved=2ahUKEwjqrZ7e88aAAxV0SWwGHRH-AyYQFnoECA0QBQ&usg=AOvVaw1fBn34y05Weg0_kg_2PDtU)
Bildschirmfoto 2023-08-06 um 09 10 16

**Comment by N3v1** [comment]
> > Looks like there is a way to perform the action using GitHub Desktop. [Reference] (https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits-in-github-desktop%23:~:text%3DSquashing%2520a%2520commit,-In%2520GitHub%2520Desktop%26text%3DIn%2520the%2520list%2520of%2520branches,commits%2520using%2520Command%2520or%2520Shift%2520.&ved=2ahUKEwjqrZ7e88aAAxV0SWwGHRH-AyYQFnoECA0QBQ&usg=AOvVaw1fBn34y05Weg0_kg_2PDtU)
> 
> Bildschirmfoto 2023-08-06 um 09 10 16

Shall I create a new PR @SID262000?

**Comment by SID262000** [comment]
Yeah maybe it would be better in that case, @N3v1 to maintain a proper git log

**Pull request closed without merging**
